### ISSUE TITLE
F11全屏切换时，控制台报“offsetLeft”错误！

### ISSUE THREAD

**Issue by fenggle** [gorkys/vue-ruler-tool#11]
![微信图片_20200317170103](https://user-images.githubusercontent.com/29393440/76839704-f12b6400-6870-11ea-877e-e127250aded7.png)
切换到其他路由，按F11切换全屏时，控制台报错，见附件。但不影响使用。在使用标尺插件的路由页面没有保错。

**Comment by namecho** [comment]
我也遇到了，当前标尺页面，切换到其他页面，全屏报一样的错误。

**Comment by namecho** [comment]
![image](https://user-images.githubusercontent.com/49669810/76943237-f86a7480-6939-11ea-8ed1-c436813d57d4.png)
找点原因了，resize事件切换路由的时候没有remove，望在下个版本修复。
