### ISSUE TITLE
当参考线的父窗口位置变化时，拖动参考线错位

### ISSUE THREAD

**Issue by freedomdebug** [gorkys/vue-ruler-tool#4]
![image](https://user-images.githubusercontent.com/7620476/63399091-0555d280-c402-11e9-932b-cb454c3e1865.png)
如图111容器时可以收缩的，正常时收起，我拖动参考线正常，但我展开后拖动参考线就错位了

**Comment by freedomdebug** [comment]
topSpacing: 0, // 标尺与窗口上间距
      leftSpacing: 0, //  标尺与窗口左间距

是否这个取值应该放到computed中，
document.getElementById('verticalRuler').getBoundingClientRect().x

**Comment by gorkys** [comment]
emm.这个组件，我目前并没有在实际项目中使用过，
所以没办法修复一些在实际场景中的应用出现的bug。
如果可以，你可以将遇到的bug，在此说明后(供后来者参考)，并修复好它。
修复过后提交一个`pull requests`，我来合并请求，再发布到npm。

**Comment by freedomdebug** [comment]
稍做修改，可以了
![image](https://user-images.githubusercontent.com/7620476/63400379-28828100-c406-11e9-8174-3e6a3419ad5d.png)

![image](https://user-images.githubusercontent.com/7620476/63400371-228ca000-c406-11e9-9e8a-d40e3457839f.png)

![image](https://user-images.githubusercontent.com/7620476/63400359-199bce80-c406-11e9-9bdd-e12bab457b1d.png)
