### ISSUE TITLE
快捷键R使用后，标尺关闭了，但内容也同样不显示了。 

### ISSUE THREAD

**Issue by leehonleon** [gorkys/vue-ruler-tool#5]
如题，怎么解决，要做callback或者自己用函数控制么？

**Comment by gorkys** [comment]
不将内容放在组件内部可以暂时解决这个问题。组件bug~

**Comment by leehonleon** [comment]
能修复么， 如果我来修复可以么？？

**Comment by gorkys** [comment]
如果你能修复源码最好不过了，修改过后可以`Pull requests`。

**Comment by leehonleon** [comment]
好的， 有空， 我看看 。
我正在用这个组件。

**Comment by gorkys** [comment]
很高兴你能使用此组件并为它做出贡献。
